### ISSUE TITLE
API docs available?

### ISSUE THREAD

**Issue by Kosta-Github** [adriankumpf/alarmate#32]
Do you have access to some API docs for that alarm system? Your constants.rs file looks like you retrieved the list of possible values from somewhere...

I did something similar from reverse engineering the responses, based on TypeScript, and for connecting the alarm system to my home mqtt event bus, which also allows me to control it with siri...

**Comment by adriankumpf** [comment]
Unfortunately, there is no proper documentation afaik. I have extracted the values from a js file with translations as described in this commit:  c97478fd398f487bf430abf8f52ea23cf6a2f08f
